import { Button } from "flowbite-react";
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Events from "../components/Events";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Eventsider | Plan your Event </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="isolate flex  flex-col items-center justify-center gap-10 p-5">
        <div className="absolute inset-x-0 top-[-10rem] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[-20rem]">
          <svg
            className="relative left-[calc(50%-11rem)] -z-10 h-[21.1875rem] max-w-none -translate-x-1/2 rotate-[30deg] sm:left-[calc(50%-30rem)] sm:h-[42.375rem]"
            viewBox="0 0 1155 678"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              fill="url(#45de2b6b-92d5-4d68-a6a0-9b9b2abad533)"
              fillOpacity=".3"
              d="M317.219 518.975L203.852 678 0 438.341l317.219 80.634 204.172-286.402c1.307 132.337 45.083 346.658 209.733 145.248C936.936 126.058 882.053-94.234 1031.02 41.331c119.18 108.451 130.68 295.337 121.53 375.223L855 299l21.173 362.054-558.954-142.079z"
            />
            <defs>
              <linearGradient
                id="45de2b6b-92d5-4d68-a6a0-9b9b2abad533"
                x1="1155.49"
                x2="-78.208"
                y1=".177"
                y2="474.645"
                gradientUnits="userSpaceOnUse"
              >
                <stop stopColor="#9089FC" />
                <stop offset={1} stopColor="#FF80B5" />
              </linearGradient>
            </defs>
          </svg>
        </div>
        <div className="mx-auto flex min-h-screen w-full max-w-screen-xl flex-col items-center justify-evenly gap-10 lg:flex-row lg:gap-5">
          <div className="max-w-xl space-y-3  text-center">
            <h1 className="mb-4 flex w-full  items-start justify-center gap-2 text-center  text-4xl font-extrabold text-gray-900 dark:text-white md:text-6xl lg:justify-start lg:text-left  lg:text-7xl">
              <span className="bg-gradient-to-r from-sky-400 to-blue-600 bg-clip-text text-transparent">
                Eventsider
              </span>{" "}
              <span className="mr-2 ml-2 rounded bg-blue-100 px-2.5 py-0.5 text-xl font-semibold text-blue-800 dark:bg-blue-200 dark:text-blue-800 sm:text-2xl">
                PRO
              </span>
            </h1>
            <h2 className="spacing-x-2 text-center text-lg font-semibold sm:text-2xl lg:text-left lg:text-3xl">
              Your One Stop for Event Registration!
            </h2>
            <p className="inline-flex items-center gap-2  text-center text-sm opacity-80 lg:text-left lg:text-lg">
              <span>
                Welcome to Eventsider! The online platform to easily find and
                register for your favorite events. Whether you’re looking for a
                music festival, conference, or something else, Eventsider is the
                perfect place to search and sign up for events near you
              </span>
            </p>
            <div className="w-full lg:text-left">
              <Link
                href="#"
                className="group inline-flex items-center   font-medium text-blue-600 hover:underline dark:text-blue-500 "
              >
                Register Now
                <svg
                  aria-hidden="true"
                  className="delay-50 ml-1 h-5 w-5 transition-transform duration-300 ease-in-out group-hover:translate-x-1"
                  fill="currentColor"
                  viewBox="0 0 20 20"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    fillRule="evenodd"
                    d="M12.293 5.293a1 1 0 011.414 0l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-2.293-2.293a1 1 0 010-1.414z"
                    clipRule="evenodd"
                  ></path>
                </svg>
              </Link>
            </div>
          </div>
          <Image
            className="delay-50 select-none transition-transform duration-500 ease-in-out hover:scale-105 "
            src="/images/hero.svg"
            alt="Hero"
            width={500}
            height={500}
          />
          <div className="absolute inset-x-0 top-[calc(100%-13rem)] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[calc(100%-30rem)]">
            <svg
              className="relative left-[calc(50%+3rem)] h-[21.1875rem] max-w-none -translate-x-1/2 sm:left-[calc(50%+36rem)] sm:h-[42.375rem]"
              viewBox="0 0 1155 678"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                fill="url(#ecb5b0c9-546c-4772-8c71-4d3f06d544bc)"
                fillOpacity=".3"
                d="M317.219 518.975L203.852 678 0 438.341l317.219 80.634 204.172-286.402c1.307 132.337 45.083 346.658 209.733 145.248C936.936 126.058 882.053-94.234 1031.02 41.331c119.18 108.451 130.68 295.337 121.53 375.223L855 299l21.173 362.054-558.954-142.079z"
              />
              <defs>
                <linearGradient
                  id="ecb5b0c9-546c-4772-8c71-4d3f06d544bc"
                  x1="1155.49"
                  x2="-78.208"
                  y1=".177"
                  y2="474.645"
                  gradientUnits="userSpaceOnUse"
                >
                  <stop stopColor="#9089FC" />
                  <stop offset={1} stopColor="#FF80B5" />
                </linearGradient>
              </defs>
            </svg>
          </div>
        </div>
        <div className="flex w-full max-w-screen-xl flex-col items-center justify-center gap-10">
          <Events />
        </div>
      </main>
    </>
  );
};

export default Home;
